export const GET_AUTH_USER = 'GET_AUTH_USER';
export const GET_AUTH_USER_SUCCESS = 'GET_AUTH_USER_SUCCESS';
export const GET_AUTH_USER_FAIL = 'GET_AUTH_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_CHANGE = 'UPDATE_CHANGE';
export const UPDATE_CHANGE_SUCCESS = 'UPDATE_CHANGE_SUCCESS';
export const UPDATE_CHANGE_FAIL = 'UPDATE_CHANGE_FAIL';

export const UPDATE_CHANGE_OPTIONS = 'UPDATE_CHANGE_OPTIONS';

export const CLEAN_MESSAGES = 'CLEAN_MESSAGES';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const UPDATE_FORM_MODAL = 'UPDATE_FORM_MODAL';

export const SUBMIT_NEW_POST = 'SUBMIT_NEW_POST';
export const SUBMIT_NEW_POST_SUCCESS = 'SUBMIT_NEW_POST_SUCCESS';
export const SUBMIT_NEW_POST_FAIL = 'SUBMIT_NEW_POST_FAIL';

export const INIT_GALLERY = 'INIT_GALLERY';
export const INIT_GALLERY_SUCCESS = 'INIT_GALLERY_SUCCESS';
export const INIT_GALLERY_FAIL = 'INIT_GALLERY_FAIL';

export const RESET_POST_DATA = 'RESET_POST_DATA';

export const SEARCH_FOR_POST = 'SEARCH_FOR_POST';
export const UPDATE_GALLERY = 'UPDATE_GALLERY';

export const INIT_MY_GALLERY = 'INIT_MY_GALLERY';
export const INIT_MY_GALLERY_SUCCESS = 'INIT_MY_GALLERY_SUCCESS';
export const INIT_MY_GALLERY_FAIL = 'INIT_MY_GALLERY_FAIL';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const DELETE_MY_GALLERY_POST = 'DELETE_MY_GALLERY_POST';
export const DELETE_MY_GALLERY_POST_SUCCESS = 'DELETE_MY_GALLERY_POST_SUCCESS';
export const DELETE_MY_GALLERY_POST_FAIL = 'DELETE_MY_GALLERY_POST_FAIL';
